### PR TITLE
Add target to document change callback

### PR DESCRIPTION
**Pull request by davidbrochart**
Needs https://github.com/jupyter-server/jupyter_ydoc/pull/122.

### CODE REVIEW

**Comment by hbcarlos** [comment]
@davidbrochart Is this PR done? I need to update JupyterLab to ydoc v0.3.

**Comment by davidbrochart** [comment]
Oh I forgot about it, yes it's ready for review.

**Review by hbcarlos — APPROVED** [review]
Thanks!

**Comment by davidbrochart** [comment]
I'll make a release now.

**Comment by davidbrochart** [comment]
Ah but we need `jupyter_ydoc >=0.3.0a5`, right?

**Pull request merged**
